[package]
name = "pact_graphql_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
pact_plugin_driver = { version = "0.4", package = "pact-plugin-driver" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
thiserror = "1"
urlencoding = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
anyhow = "1"

[dev-dependencies]
pretty_assertions = "1"
